### ISSUE TITLE
Support for basic auth

### ISSUE THREAD

**Issue by sajoupa** [CanonicalLtd/docker-registry-charm#11]
The charm currently supports only authentication with a token server.
A common implementation uses native basic authentication with htpasswd: https://docs.docker.com/registry/deploying/#native-basic-auth
The authentication info could then be passed to kubernetes-worker through the relation.

**Comment by tvansteenburgh** [comment]
Moved to https://bugs.launchpad.net/layer-docker-registry/+bug/1788892
